Antigen, le gestionnaire de paquets pour zsh
Evaneos/le-truc pull request #14
Opened 2018-03-12 16:00 UTC by alepee

2018-03-12 17:10 UTC, fhuitelec requested changes

2018-03-12 17:10 UTC, fhuitelec commented on _posts/2018-03-13-antigen-le-gestionnaire-de-paquets-pour-zsh.md
> +summary: "Antigen est un ensemble de fonctions qui permettent de gérer facilement les modules de votre shell zsh. Le concept est pratiqement le même que les bundles vim+pathogen."
`pratiquement`

2018-03-12 17:10 UTC, fhuitelec commented on _posts/2018-03-13-antigen-le-gestionnaire-de-paquets-pour-zsh.md
> +    - Unix
Tu peux ajouter `antigen` et/ou `dotfiles` dans les tags, y'a quelques tips `antigen` que j'aimerais poster et ça permettra de les catégoriser simplement.

2018-03-12 17:10 UTC, fhuitelec commented on _posts/2018-03-13-antigen-le-gestionnaire-de-paquets-pour-zsh.md
> +```zsh
Ca peut valoir le coup d'ajouter que ça se trouve dans `~/.zshrc`.

2018-03-12 17:10 UTC, fhuitelec commented on _posts/2018-03-13-antigen-le-gestionnaire-de-paquets-pour-zsh.md
> +[Antigen](http://github.com/zsh-users/antigen) est un ensemble de fonctions qui permettent de gérer facilement les modules de votre shell zsh. Le concept est pratiqement le même que les bundles `vim+
Same pour `pratiquement`. On peut même reformuler en `le concept est équivalent aux bundles [...]`.

2018-03-12 17:10 UTC, fhuitelec commented on _posts/2018-03-13-antigen-le-gestionnaire-de-paquets-pour-zsh.md
> +# Homebrew
Ajouter un `Installer via` avant **Homebrew** et **cURL**, on distingue pas facilement que ce sont 2 alternatives d'installation.

2018-03-12 17:10 UTC, fhuitelec commented on _posts/2018-03-13-antigen-le-gestionnaire-de-paquets-pour-zsh.md
> +La liste des approches pour installer antigen est disponible sur le [wiki du repo](https://github.com/zsh-users/antigen/wiki/Installation).
~~sur~~ dans/au sein du

2018-03-12 17:10 UTC, fhuitelec commented on _posts/2018-03-13-antigen-le-gestionnaire-de-paquets-pour-zsh.md
> +```zsh
Same : indiquer que c'est dans `.zshrc` pour donner un peu de contexte 🙂

2018-03-12 17:10 UTC, fhuitelec commented on _posts/2018-03-13-antigen-le-gestionnaire-de-paquets-pour-zsh.md
> +# Tell antigen i'm done
`I'm` avec un `I`

2018-03-12 17:10 UTC, fhuitelec commented on _posts/2018-03-13-antigen-le-gestionnaire-de-paquets-pour-zsh.md
> +# Tell antigen i'm done
Same: `I'm` avec un `I`

2018-03-12 17:26 UTC, ProPheT777 commented
si ça peut donner des idées perso j'utilise : 

```cmd
antigen use oh-my-zsh
antigen bundle git
antigen bundle pip
antigen bundle command-not-found
antigen bundle docker-compose
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme refined
antigen bundle bobsoppe/zsh-ssh-agent
antigen bundle desyncr/auto-ls
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle github
antigen bundle colorize
antigen apply
```

2018-03-28 12:54 UTC, fhuitelec approved these changes
Au poil 👌

2018-03-28 12:54 UTC, merged