Remove composer polyfill when useless
Evaneos/le-truc pull request #3
Opened 2018-02-06 16:55 UTC by ProPheT777

2018-02-06 16:56 UTC, kurlzor commented on _posts/2018-01-25-composer-and-symfony-polyfill.md
> +Si vous êtes en 7.2 vous pouvez éviter de charger de les polyfills vous pouvez ajouter la section "replace" dans composer :
de charger de

2018-02-06 16:56 UTC, kurlzor commented on _posts/2018-01-25-composer-and-symfony-polyfill.md
> +title: Eviter de charger les polyfill inutile grâce à composer
inutiles

2018-02-06 16:57 UTC, kurlzor commented on _posts/2018-01-25-composer-and-symfony-polyfill.md
> +summary: "Supprimé les polyfill inutiles"
Supprimer

2018-02-06 16:59 UTC, qpautrat requested changes

2018-02-06 16:59 UTC, qpautrat commented on _posts/2018-01-25-composer-and-symfony-polyfill.md
> +summary: "Supprimé les polyfill inutiles"
*Supprimer*

2018-02-06 16:59 UTC, qpautrat commented on _posts/2018-01-25-composer-and-symfony-polyfill.md
> +Si vous êtes en 7.2 vous pouvez éviter de charger de les polyfills vous pouvez ajouter la section "replace" dans composer :
*... de charger les polyfills en ajoutant ...* ?

2018-02-06 16:59 UTC, qpautrat commented on _posts/2018-01-25-composer-and-symfony-polyfill.md
> +puis jouer la command `composer update` afin de les supprimer. A vous d'ajuster les polyfill à supprimer en fonction de votre version.
*Enfin il suffit de jouer la command...* ?

2018-02-06 17:01 UTC, SelrahcD commented on _posts/2018-01-25-composer-and-symfony-polyfill.md
> +Si vous êtes en 7.2 vous pouvez éviter de charger de les polyfills vous pouvez ajouter la section "replace" dans composer :
Je rajouterais une intro disant que SF rajoute des polyfills pour la rétro compat :)

2018-02-06 17:14 UTC, kurlzor commented on _posts/2018-01-25-composer-and-symfony-polyfill.md
> +Symfony ajoute des polyfill pour des histoires compatibilités, sans que ça ne soit forcément utiles. Si vous êtes en 7.2 vous pouvez éviter de charger les polyfills vous pouvez ajouter la section "re
histoires **de** compatibilité**~s~** 😂

2018-02-06 17:21 UTC, SelrahcD commented on _posts/2018-01-25-composer-and-symfony-polyfill.md
> +summary: "Supprimé les polyfill inutiles"
Est-ce que tu peux essayer de faire une description un peu plus longue ? Il s'agit du texte qui sera affiché dans la card sur slack. L'idée c'est d'avoir une idée du sujet. Que penses-tu de quelque chose comme `Comment éviter d'installer les polyfills de Symfony alors qu'ils sont inutiles en PHP 7.2 ?` ?

2018-02-12 09:51 UTC, SelrahcD commented
@ProPheT777 Pipou encore ? Tu veux un coup de main pour finir ? :)

2018-02-12 13:43 UTC, ProPheT777 commented
tout est corrigé non ? en tout cas tout les cas sont masqués chez moi, il reste quoi ?

2018-02-12 16:34 UTC, merged